baseURL = 'https://learningtosqi.github.io'
languageCode = 'en-us'
title = "Learning to SQI"
theme = 'cleanmaths'

[params]
  description = "Implementing SQISign in SageMath"
  authors = ["Maria Corte-Real Santos,", "Giacomo Pope"]
  [params.theme_config]
    show_description = true

  [[params.social]]
      title = "GitHub"
      link = "https://github.com/jack4818/SQISign-SageMath"
      icon = "/images/github.svg"

[markup]
  [markup.highlight]
    style = 'gruvbox'